dataset:
  observation_fieldnames:
     - index
     - sentence
     - lemma_sentence
     - upos_sentence
     - xpos_sentence
     - morph
     - head_indices
     - governance_relations
     - secondary_relations
     - extra_info
     - embeddings
  corpus:
    root: data/
    train_path: train.conllx
    dev_path: dev.conllx
    test_path: test.conllx
  embeddings:
    type: subword #{token,subword}, ignored
    root: data/ 
    train_path: train.bert-layers.hdf56
    dev_path: dev.bert-layers.hdf56
    test_path: test.bert-layers.hdf56
  batch_size: 20
model:
  hidden_dim: 768 # base 768, large 1024
  #embedding_dim: 1024 # ignored
  model_type: ELMo-disk # BERT-disk, ELMo-disk, 
  use_disk: True
  model_layer: 0 # BERT-base: {1,...,12}; ELMo: {1,2,3}
probe:
  task_signature: word # word, word_pair
  task_name: parse-depth
  maximum_rank: 768 # base 768, large 1024
  psd_parameters: True
  diagonal: False # ignored
  params_path: predictor.params
probe_training:
  epochs: 30
  loss: L1
reporting:
  root: example/results
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictions
  reporting_methods:
    - spearmanr
    - image_examples
    - root_acc
